### ISSUE TITLE
tread 'main' panicked - pyrometer ./src/name.sol

### ISSUE THREAD

**Issue by 0xUnkn0wN** [nascentxyz/pyrometer#17]
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/lib.rs:401:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

The file exist.

**Comment by dmel642** [comment]
Having same error too

**Comment by brockelmore** [comment]
Can one of you make a minimal repro please?

This is around imports, so a basic foundry repo with a reproduction would be greatly appreciated

**Comment by dmel642** [comment]
> Can one of you make a minimal repro please?
> 
> This is around imports, so a basic foundry repo with a reproduction would be greatly appreciated

Here are the exact steps I took. I installed the latest version of Ziion into Virtualbox: 
https://www.ziion.org/

Then I followed the instructions and ran command to install rust. Then I cd into the folder and ran the cargo install command. 

When I test pyrometer on one of the sample contracts such as matic using command `pyrometer '/home/ziion/Desktop/pyrometer/matic.sol'`

It works just fine. But when I download any semi-complicated smart contract that has dependencies, such as this one:
https://bscscan.com/address/0x36b34364e17373C05300Bc3e827BF7cac34541BE#code

I get the following error 
![issue1](https://user-images.githubusercontent.com/68926642/229330717-9495d5f8-f3f8-4af5-adb8-dfd9d5f37874.jpg)

I downloaded the contract using BlockSec's MetaDock extension. The files are all there: 
![issue2](https://user-images.githubusercontent.com/68926642/229330739-ea387e0c-b7d8-42d3-b95e-960ff8ec4dcb.jpg)

I've tried multiple contracts, and I can't get it to work on them. Even when I limit function output to one. 

Wait, do you mean I need to have the files in a foundry project in order for the tool to work? I did not know that.

**Comment by 0xUnkn0wN** [comment]
I tried it with my public project:

https://github.com/0xUnkn0wN/NounsTrade

**Comment by brockelmore** [comment]
> Wait, do you mean I need to have the files in a foundry project in order for the tool to work? I did not know that.


No but based on the issue title and the location of the import "src/name.sol" I figured it was already a foundry repo. I'll take a look based on the public repo in the other reply. Thanks! Will try to get this fixed today

**Comment by brockelmore** [comment]
This should be fixed on the #18 branch. Can each of you try out that branch and report back?

@0xUnkn0wN the issue with yours was that you definitely had an old version - but there was a secondary issue related to cyclic dependencies (i.e. A imports B and B imports A). We now handle this correctly I believe.

@dmel642 That setup requires too many steps for me to address right now - do you mind just creating a github repo i can clone easily? Thanks (unless the #18 branch fixes your issues)

**Comment by 0xUnkn0wN** [comment]
> This should be fixed on the #18 branch. Can each of you try out that branch and report back?
> 
> 
> 
> @0xUnkn0wN the issue with yours was that you definitely had an old version - but there was a secondary issue related to cyclic dependencies (i.e. A imports B and B imports A). We now handle this correctly I believe.
> 
> 
> 
> @dmel642 That setup requires too many steps for me to address right now - do you mind just creating a github repo i can clone easily? Thanks (unless the #18 branch fixes your issues)

I will check that out tomorrow and report back.

**Comment by 0xUnkn0wN** [comment]
@brockelmore i have switched to the brock/variety branch and rebuilded, but still the same error.

**Comment by brockelmore** [comment]
Right you actually have to pass in the remappings file - I should have mentioned this. 

@0xUnkn0wN adding `--remappings ./remappings.txt` should fix the issue. I'll surface this issue

**Comment by patrickd-** [comment]
Ah, okay. With the remappings I get a different error now :sweat_smile: 

```
$ pyrometer -r remappings.txt src/Contract.sol
thread 'main' panicked at 'Expected a single return got: Multi([])', src/context/mod.rs:44:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by patrickd-** [comment]
Unfortunately it' from a closed source audit. FYI that error only happens for #18. With master it overflows:

```NodeIndex(172676)
NodeIndex(172717)
NodeIndex(172787)
NodeIndex(172828)
NodeIndex(172857)
NodeIndex(172898)

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
Aborted
```

The project is rather complex, so I'm not surprised. Thanks though!

**Comment by brockelmore** [comment]
@patrickd- If you use recursive function calls, thats not supported - we currently don't limit call depth

**Comment by brown-qs** [comment]
Same error encountered.
Any solutions?
